index:
    path: /home
    controller: App\Controller\HomeController::index

kamers:
    path: /kamers
    controller: App\Controller\KamersController::index

kamer1:
  path: /kamer1
  controller: App\Controller\KamersController::index
